package:
  name: embedded-cluster-operator
  version: ${VERSION}
  epoch: 0
  description: Embedded Cluster Operator
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - go

pipeline:
  - runs: |
      set -exuo pipefail

      make build
      cp bin/manager "${{targets.contextdir}}/manager"
  - uses: strip
