apiVersion: batch/v1
kind: Job
metadata:
  namespace: embedded-cluster
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccount: embedded-cluster-operator
      serviceAccountName: embedded-cluster-operator
      volumes:
      - name: host
        hostPath:
          path: /var/lib/embedded-cluster
          type: Directory
      restartPolicy: Never
      containers:
      - name: embedded-cluster-updater
        image: busybox:latest
        volumeMounts:
        - mountPath: /var/lib/embedded-cluster
          name: host
          readOnly: false
        command:
        - /bin/sh
        - -e
        - -c
        - |
          /var/lib/embedded-cluster/bin/local-artifact-mirror pull binaries $INSTALLATION
          /var/lib/embedded-cluster/bin/local-artifact-mirror pull images $INSTALLATION
          /var/lib/embedded-cluster/bin/local-artifact-mirror pull helmcharts $INSTALLATION
