name: 'Build and push a custom image with apko'
description: 'Composite action for building and pushing a custom image with apko'
inputs:
  component:
    description: 'Name of the component'
    required: true

  config:
    description: 'Path to the apko config file'
    required: true

  archs:
    description: 'Architectures to build for'
    required: true

  image-name:
    description: 'Full destination image name'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.component }}-melange-packages
        path: ./packages/
        merge-multiple: true

    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.component }}-melange-rsa-pub
        merge-multiple: true

    - uses: chainguard-images/actions/apko-publish@main
      with:
        config: ${{ inputs.config }}
        archs: ${{ inputs.archs }}
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
