apiVersion: v1
kind: ConfigMap
metadata:
  name: embedded-cluster-cluster-support-bundle
  labels:
    troubleshoot.sh/kind: support-bundle
data:
  support-bundle-spec: {{ .Files.Get "troubleshoot/cluster-support-bundle.yaml" | quote }}
