apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ (include "embedded-cluster-operator.fullname" $) | trunc 63 | trimAll "-" }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
