apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ (include "embedded-cluster-operator.fullname" $) | trunc 63 | trimAll "-" }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - embeddedcluster.replicated.com
  resources:
  - installations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - embeddedcluster.replicated.com
  resources:
  - installations/finalizers
  verbs:
  - update
- apiGroups:
  - embeddedcluster.replicated.com
  resources:
  - installations/status
  verbs:
  - get
  - patch
  - update
