name: publish-production
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+\-build\.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build
      run: |
        export VERSION=${{steps.tag.outputs.tag}}
        make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: manager
        path: ./bin/manager

  package-and-publish-operator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Build melange package
      run: |
        export VERSION=${{steps.tag.outputs.tag}}
        make melange
    - name: Publish apko image
      run: |
        export VERSION=${{steps.tag.outputs.tag}}
        export IMAGE=registry.replicated.com/library/embedded-cluster-operator-image:${VERSION}
        make apko-login \
          REGISTRY=registry.replicated.com \
          USERNAME=${{secrets.KOTS_HELM_USER_PROD}} \
          PASSWORD=${{secrets.KOTS_HELM_PASS_PROD}}
        make apko-publish
        echo ::notice title=digest::$(cat build/digest)

  package-and-publish-helmchart:
    runs-on: 'ubuntu-20.04'
    needs: [package-and-publish-operator]
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.8.1
    - name: Run Package and Publish
      working-directory: charts/embedded-cluster-operator
      env:
        HELM_USER: ${{secrets.KOTS_HELM_USER_PROD}}
        HELM_PASS: ${{secrets.KOTS_HELM_PASS_PROD}}
        HELM_REGISTRY: registry.replicated.com
        CHART_VERSION: ${{steps.tag.outputs.tag}}
      run: |
        export OPERATOR_IMAGE_NAME=registry.replicated.com/library/embedded-cluster-operator-image
        export OPERATOR_IMAGE_TAG=${CHART_VERSION}
        export CHART_REMOTE=oci://registry.replicated.com/library

        ../../scripts/publish-helm-chart.sh

  releaser:
    runs-on: ubuntu-latest
    needs: [build, package-and-publish-helmchart]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: manager
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/manager
